language: node_js
before_install:
  npm install now
deploy: 
  provider: script
  script: npm start
  skip_cleanup: true
  on:
    branch: master
cache:
  directories: 
    - jest/tmp
    - node_modules
